In [4]:
import numpy as np
import pandas as pd

In [5]:
df= pd.read_csv('customer_shopping_behavior.csv')

In [6]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             70000 non-null  int64
 1   Age                     70000 non-null  int64
 2   Gender                  70000 non-null  str
 3   Item Purchased          70000 non-null  str
 4   Category                70000 non-null  str
 5   Purchase Amount (USD)   70000 non-null  int64
 6   Location                70000 non-null  str
 7   Size                    70000 non-null  str
 8   Color                   70000 non-null  str
 9   Season                  70000 non-null  str
 10  Review Rating           69326 non-null  float64
 11  Subscription Status     70000 non-null  str
 12  Shipping Type           70000 non-null  str
 13  Discount Applied        70000 non-null  str
 14  Promo Code Used         70000 non-null  str
 15  Previous Purchases      70000 non-null  int64
 16  Payment Method          70000 non-null  str
 17  Frequency of Purchases  70000 non-null  str
dtypes: float64(1), int64(4), str(13)
memory usage: 9.6 MB

In [8]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,70000.000000,70000.000000,70000,70000,70000,70000.000000,70000,70000,70000,70000,69326.000000,70000,70000,70000,70000,70000.000000,70000,70000
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,California,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,47470,3129,31269,NaN,1734,31714,3175,17955,NaN,51237,12204,39976,39976,NaN,12211,10579
mean,35000.500000,44.090871,NaN,NaN,NaN,59.551957,NaN,NaN,NaN,NaN,3.749358,NaN,NaN,NaN,NaN,25.446314,NaN,NaN
std,20207.403759,15.224922,NaN,NaN,NaN,23.663321,NaN,NaN,NaN,NaN,0.721551,NaN,NaN,NaN,NaN,14.463490,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,17500.750000,31.000000,NaN,NaN,NaN,38.000000,NaN,NaN,NaN,NaN,3.125287,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,35000.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.753479,NaN,NaN,NaN,NaN,26.000000,NaN,NaN
75%,52500.250000,57.000000,NaN,NaN,NaN,80.000000,NaN,NaN,NaN,NaN,4.364168,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,70000.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [9]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)       0
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating             674
Subscription Status         0
Shipping Type               0
Discount Applied            0
Promo Code Used             0
Previous Purchases          0
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [10]:
df['Review Rating']= df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

In [11]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [12]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df=df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})

In [13]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [14]:
# Create a column age_group
labels= ['Young Adult', 'Adult','Middle-aged','Senior']
df['age_group']=pd.qcut(df['age'],q=4, labels=labels)

In [15]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [16]:
# Create column purchase_frequency_days

frequency_mapping={
    'Fortnightly': 14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90
}

df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [17]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [18]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [19]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [20]:
df=df.drop('promo_code_used', axis=1)

In [21]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [28]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

# Step1: Connect to PostgreSQL
# Replace placeholders with your actual details
username= "postgres"  #default user
password = quote_plus("#Panu@_1167")
host="localhost"
port="5432"
database="customer_shopping_behavior"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

#Step2: Load Dataframe into PostgreSQL
table_name="customer" #Choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data succesfully loaded into table '{table_name}' in database '{database}'.")

Data succesfully loaded into table 'customer' in database 'customer_shopping_behavior'.